apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium.yaml
  - lb-ip-pool.yaml
  - l2-announcement-policy.yaml
  - cilium-monitoring.yaml
  - hubble-ui-certificate.yaml
  - hubble-ui-ingressroute.yaml
