apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blocky-pg
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  instances: 3
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: blocky
      owner: blocky
      secret:
        name: pg-app-user-blocky
  storage:
    storageClass: ceph-block
    size: 5Gi
