apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg-cluster
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  instances: 3
  enableSuperuserAccess: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: wasabi-object-store
        serverName: authentik-pg-cluster-geekzoo-prod-20260401
  bootstrap:
    recovery:
      source: authentik-pg-cluster-restore
  externalClusters:
    - name: authentik-pg-cluster-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: wasabi-object-store
          serverName: authentik-pg-cluster-geekzoo-prod
  storage:
    storageClass: ceph-block
    size: 10Gi
