apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls-certificate
  namespace: media
spec:
  secretName: prowlarr-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.macbytes.io
