apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: cloudflared
    namespace: system
    files:
      - config.yaml=cloudflared-config.yaml

generatorOptions:
  disableNameSuffixHash: false
