apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-rgw-certificate
  namespace: rook-ceph
spec:
  secretName: ceph-rgw-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - s3.macbytes.io
