apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: groundcover
  labels:
    name: groundcover
---
apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    name: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    name: rook-ceph
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    name: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    name: velero
