apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls-certificate
  namespace: media
spec:
  secretName: qbittorrent-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - torrent.macbytes.io
