apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
      annotations:
        backup.velero.io/backup-volumes-excludes: qbittorrent-media
    spec:
      securityContext:
        fsGroup: 65533
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-gluetun
          persistentVolumeClaim:
            claimName: qbittorrent-gluetun-pvc
        - name: qbittorrent-media
          persistentVolumeClaim:
            claimName: pvc-media-nfs
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:v3.41.1 # {"$imagepolicy": "flux-system:gluetun-image-policy"}
          imagePullPolicy: IfNotPresent
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-qbittorrent-vpn
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-qbittorrent-vpn
                  key: OPENVPN_PASSWORD
            - name: VPN_PORT_FORWARDING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pia-qbittorrent-vpn
                  key: OPENVPN_USER
            - name: VPN_PORT_FORWARDING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-qbittorrent-vpn
                  key: OPENVPN_PASSWORD
            - name: SERVER_REGIONS
              value: "ca montreal"
            - name: PORT_FORWARD_ONLY
              value: "true"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_STATUS_FILE
              value: "/gluetun/forwarded_port"
            - name: TZ
              value: "America/New_York"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: FIREWALL
              value: "off"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: qbittorrent-gluetun
              mountPath: /gluetun
            - name: qbittorrent-bootstrap
              mountPath: /bootstrap
            - name: dev-net-tun
              mountPath: /dev/net/tun
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:20.04.1 # {"$imagepolicy": "flux-system:qbittorrent-image-policy"}
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65533"
            - name: TZ
              value: "America/New_York"
            - name: WEBUI_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - name: http
              containerPort: 8080
            - name: peer-tcp
              containerPort: 6881
            - name: peer-udp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-media
              mountPath: /media
            - name: qbittorrent-gluetun
              mountPath: /gluetun
              readOnly: true
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SETGID
                - SETUID
        - name: mousehole
          image: tmmrtn/mousehole:latest # {"$imagepolicy": "flux-system:mousehole-image-policy"}
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
            - name: MOUSEHOLE_PORT
              value: "5010"
          ports:
            - name: mousehole-http
              containerPort: 5010
              protocol: TCP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /srv/mousehole
              subPath: mousehole
