apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: plane-pg-cluster
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  instances: 3
  enableSuperuserAccess: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: aws-object-store
        serverName: plane-pg-cluster-geekzoo-prod
  bootstrap:
    initdb:
      database: plane
      owner: plane
      secret:
        name: pg-app-user-plane
  storage:
    storageClass: ceph-block
    size: 20Gi
