apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-certificate
  namespace: identity
spec:
  secretName: authentik-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - authentik.macbytes.io
