apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: media-image-updates
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-image-automation@macbytes.io
        name: flux-image-automation
      messageTemplate: 'chore(images): update media app container images'
    push:
      branch: main
  update:
    path: ./media
    strategy: Setters
