apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: qbittorrent-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  policy:
    semver:
      range: ">=4.0.0"
