apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: radarr-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: ">=6.0.0"
