apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: prowlarr-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
  filterTags:
    pattern: '^release-(?P<major>[0-9]+)\.(?P<minor>[0-9]+)\.(?P<patch>[0-9]+)\.(?P<build>[0-9]+)$'
    extract: '$major.$minor.$patch-$build'
  policy:
    semver:
      range: ">=1.10.5-0"
