apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mousehole-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mousehole
  policy:
    alphabetical:
      order: desc
