apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - image-repository-gluetun.yaml
  - image-repository-adguardhome.yaml
  - image-repository-bazarr.yaml
  - image-repository-jellyfin.yaml
  - image-repository-qbittorrent.yaml
  - image-repository-prowlarr.yaml
  - image-repository-radarr.yaml
  - image-repository-sonarr.yaml
  - image-repository-mousehole.yaml
  - image-repository-sabnzbd.yaml
  - image-repository-unpackerr.yaml
  - image-repository-vaultwarden.yaml
  - image-policy-gluetun.yaml
  - image-policy-adguardhome.yaml
  - image-policy-bazarr.yaml
  - image-policy-jellyfin.yaml
  - image-policy-qbittorrent.yaml
  - image-policy-prowlarr.yaml
  - image-policy-radarr.yaml
  - image-policy-sonarr.yaml
  - image-policy-mousehole.yaml
  - image-policy-sabnzbd.yaml
  - image-policy-unpackerr.yaml
  - image-policy-vaultwarden.yaml
  - image-update-automation.yaml
  - image-update-automation-apps.yaml
