apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-pushover
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        user_key: "{{ .user_key }}"
        api_token: "{{ .api_token }}"
  data:
    - secretKey: user_key
      remoteRef:
        key: /k3s-geekzoo/alertmanager-pushover/user-key
    - secretKey: api_token
      remoteRef:
        key: /k3s-geekzoo/alertmanager-pushover/api-token
