apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-pushover
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        user_key: "{{ .user_key }}"
        api_token: "{{ .api_token }}"
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by:
              - alertname
              - cluster
              - namespace
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: pushover
          receivers:
            - name: pushover
              pushover_configs:
                - user_key: "{{ .user_key }}"
                  token: "{{ .api_token }}"
                  title: Geekzoo Talos alert
                  message: Alertmanager has a firing or resolved alert. Check Grafana for details.
                  priority: "1"
  data:
    - secretKey: user_key
      remoteRef:
        key: /k3s-geekzoo/alertmanager-pushover/user-key
    - secretKey: api_token
      remoteRef:
        key: /k3s-geekzoo/alertmanager-pushover/api-token
