apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifactsctl-secrets
  namespace: artifactsctl
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: artifactsctl
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        database-url: "postgres://artifactsctl:{{ .database_password }}@artifactsctl-pg-cluster-rw.database.svc.cluster.local:5432/artifactsctl"
        artifacts-api-key: "{{ .artifacts_api_key }}"
  data:
    - secretKey: database_password
      remoteRef:
        key: /k3s-geekzoo/pg-app-user-artifactsctl
        property: password
    - secretKey: artifacts_api_key
      remoteRef:
        key: /k3s-geekzoo/artifactsctl-api-key
