apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-redis-config
  namespace: identity
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: authentik-redis-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/redis-password
