apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: identity
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/authentik-secret-key
