apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: bifrost-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ZAI_API_KEY
      remoteRef:
        key: /k3s-geekzoo/bifrost/zai-api-key
