apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost-db-config
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: bifrost-db-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/bifrost-db-config
