apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blocky-ui-database-url
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: blocky-ui-database-url
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: "/k3s-geekzoo/blocky-ui-database-url"