apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blocky-config
  namespace: apps
  annotations:
    updated-at: "2025-08-30T15:08:28Z"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: blocky-config
    creationPolicy: Owner
  data:
    - secretKey: config.yml
      remoteRef:
        key: "/k3s-geekzoo/blocky.yml"