apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-certmanager-secret
  namespace: system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-certmanager-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/cloudflare-certmanager-secret
