apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-secret-values
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: clickstack-secret-values
    creationPolicy: Owner
  data:
    - secretKey: HYPERDX_API_KEY
      remoteRef:
        key: /k3s-geekzoo/clickstack-hyperdx-api-key
        property: HYPERDX_API_KEY
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/clickstack-clickhouse-password
        property: CLICKHOUSE_PASSWORD
    - secretKey: CLICKHOUSE_APP_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/clickstack-clickhouse-app-password
        property: CLICKHOUSE_APP_PASSWORD
    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/clickstack-mongodb-password
        property: MONGODB_PASSWORD
