apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/cloudflared-tunnel-credentials
