apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-wasabi-credentials
  namespace: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: cnpg-wasabi-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/cnpg-wasabi-credentials
