---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-enroll-key
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: crowdsec-enroll-key
    creationPolicy: Owner
  data:
  - secretKey: enroll-key
    remoteRef:
      key: /k3s-geekzoo/crowdsec-enroll-key
