apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-api
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: security
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: crowdsec-bouncer-api
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: /k3s-geekzoo/crowdsec/bouncer-api-key
