apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dash0-authorization-secret
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: dash0-authorization-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/dash0-authorization-secret
