apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-otlp-auth
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-otlp-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{"{{"}} .username {{"}}"}}"
        password: "{{"{{"}} .password {{"}}"}}"
  data:
    - secretKey: username
      remoteRef:
        key: /k3s-geekzoo/grafana-cloud-otlp-username
    - secretKey: password
      remoteRef:
        key: /k3s-geekzoo/grafana-cloud-otlp-password