apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-config
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .auth_url }}"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .token_url }}"
        GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .api_url }}"
        GF_AUTH_SIGNOUT_REDIRECT_URL: "{{ .logout_url }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_STYLE: "in_params"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || 'Viewer'"
  data:
    - secretKey: client_id
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/client-id
    - secretKey: client_secret
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/client-secret
    - secretKey: auth_url
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/auth-url
    - secretKey: token_url
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/token-url
    - secretKey: api_url
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/api-url
    - secretKey: logout_url
      remoteRef:
        key: /k3s-geekzoo/grafana-oidc/logout-url
