apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: groundcover-ingestion-key
  namespace: groundcover
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: api-key
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /k3s-geekzoo/groundcover-api-key
