apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik-database-config.yaml
  - authentik-redis-config.yaml
  - authentik-s3-storage.yaml
  - authentik-secret-key.yaml
  - certmanager-cloudflare-api.yaml
  - cloudflared-tunnel-credentials.yaml
  - clickstack-secret-values.yaml
  - cnpg-wasabi-credentials.yaml
  - crowdsec-bouncer-external-secret.yaml
  - crowdsec-enroll-external-secret.yaml
  - crowdsec-syslog-agent-external-secret.yaml
  - minecraft-rcon-external-secret.yaml
  - pg-app-user-authentik.yaml
  - pg-app-user-coder.yaml
  - pg-app-user-grafana.yaml
  - pg-app-user-vaultwarden.yaml
  - pg-app-user-seerr.yaml
  - open-webui-oidc-config.yaml
  - seerr-database-config.yaml
  - pgadmin-default-credentials.yaml
  - pgadmin-oauth-config.yaml
  - pia-qbittorrent-vpn.yaml
  - plex-secrets.yaml
  - redis-password.yaml
  - unifi-bouncer-config.yaml
  - unpackerr-conf.yaml
  - vaultwarden-config.yaml
