apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-s3-backup-credentials
  namespace: longhorn-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: longhorn-s3-backup-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/longhorn-s3-backup-credentials
