apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-secrets
  namespace: mail
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: mail-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SES_SMTP_USERNAME
      remoteRef:
        key: /k3s-geekzoo/mail/ses-smtp-username
    - secretKey: SES_SMTP_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/mail/ses-smtp-password
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        key: /k3s-geekzoo/mail/stalwart-recovery-admin
    - secretKey: FRP_TOKEN
      remoteRef:
        key: /k3s-geekzoo/mail/frp-auth-token
    - secretKey: BULWARK_SESSION_SECRET
      remoteRef:
        key: /k3s-geekzoo/mail/bulwark-session-secret
    - secretKey: BREVO_SMTP_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/mail/brevo-smtp-key
