apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediamanager-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: mediamanager-secrets
    creationPolicy: Owner
  data:
    - secretKey: pg_password
      remoteRef:
        key: /k3s-geekzoo/pg-app-user-mediamanager
        property: password
    - secretKey: token_secret
      remoteRef:
        key: /k3s-geekzoo/mediamanager/token-secret
    - secretKey: smtp_username
      remoteRef:
        key: /k3s-geekzoo/mail/ses-smtp-username
    - secretKey: smtp_password
      remoteRef:
        key: /k3s-geekzoo/mail/ses-smtp-password
