---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-rcon-password
  namespace: apps
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: authentication
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: minecraft-rcon-password
    creationPolicy: Owner
  data:
  - secretKey: rcon-password
    remoteRef:
      key: /k3s-geekzoo/minecraft/rcon-password