apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-oidc-config
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: open-webui-oidc-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OAUTH_CLIENT_SECRET
    - secretKey: OPENID_PROVIDER_URL
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OPENID_PROVIDER_URL
    - secretKey: OPENID_END_SESSION_ENDPOINT
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OPENID_END_SESSION_ENDPOINT
    - secretKey: OPENID_REDIRECT_URI
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OPENID_REDIRECT_URI
    - secretKey: OAUTH_PROVIDER_NAME
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OAUTH_PROVIDER_NAME
    - secretKey: OAUTH_SCOPES
      remoteRef:
        key: /k3s-geekzoo/open-webui-oidc/OAUTH_SCOPES
