apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openobserve-root-user
  namespace: openobserve
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: openobserve-root-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZO_ROOT_USER_EMAIL: "{{ .ZO_ROOT_USER_EMAIL }}"
        ZO_ROOT_USER_PASSWORD: "{{ .ZO_ROOT_USER_PASSWORD }}"
        OPENOBSERVE_AUTH_HEADER: Basic {{ printf "%s:%s" .ZO_ROOT_USER_EMAIL .ZO_ROOT_USER_PASSWORD | b64enc }}
        collector-values.yaml: |
          exporters:
            otlphttp/openobserve:
              endpoint: http://openobserve-openobserve-standalone.openobserve.svc.cluster.local:5080/api/default/
              headers:
                Authorization: Basic {{ printf "%s:%s" .ZO_ROOT_USER_EMAIL .ZO_ROOT_USER_PASSWORD | b64enc }}
            otlphttp/openobserve_k8s_events:
              endpoint: http://openobserve-openobserve-standalone.openobserve.svc.cluster.local:5080/api/default/
              headers:
                Authorization: Basic {{ printf "%s:%s" .ZO_ROOT_USER_EMAIL .ZO_ROOT_USER_PASSWORD | b64enc }}
                stream-name: k8s_events
  dataFrom:
    - extract:
        key: /k3s-geekzoo/openobserve-root-user
