apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-app-user-vaultwarden
  namespace: database
  annotations:
    force-sync: "2025-07-31T23:21:43Z"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pg-app-user-vaultwarden
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/pg-app-user-vaultwarden
