apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-app-user-grafana
  namespace: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pg-app-user-grafana
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/pg-app-user-grafana
