apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-passwords
  namespace: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-passwords
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: /k3s-geekzoo/pgadmin-passwords
