apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin4-oauth-config
  namespace: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pgadmin4-oauth-config
    creationPolicy: Owner
  data:
    - secretKey: config_local.py
      remoteRef:
        key: /k3s-geekzoo/pgadmin4-oauth-config/config_local.py
