apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-rabbitmq-default-user
  namespace: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: plane-rabbitmq-default-user
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/plane-rabbitmq-default-user
