apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app-secrets
  namespace: plane
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: plane-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/plane-app-secrets
