apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: plex-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/plex-secrets
