apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushover-alertmanager
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pushover-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /k3s-geekzoo/pushover-alertmanager
        property: token
    - secretKey: user_key
      remoteRef:
        key: /k3s-geekzoo/pushover-alertmanager
        property: user_key
