apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-database-config
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: seerr-database-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /k3s-geekzoo/pg-app-user-seerr
