apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-config
  namespace: media
spec:
  refreshInterval: 24h # how often ESO will refresh
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: unpackerr-config
    creationPolicy: Owner # ESO will own (create/update) it
  data:
    - secretKey: unpackerr.conf # key in the k8s Secret
      remoteRef:
        key: "/k3s-geekzoo/unpackerr.conf"
