apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: vikunja-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: VIKUNJA_DATABASE_PASSWORD
      remoteRef:
        key: /k3s-geekzoo/vikunja-secrets
        property: db-password
    - secretKey: VIKUNJA_SERVICE_SECRET
      remoteRef:
        key: /k3s-geekzoo/vikunja-secrets
        property: jwt-secret
