apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikunja-certificate
  namespace: apps
spec:
  secretName: vikunja-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vikunja.macbytes.io
