apiVersion: v1
kind: Service
metadata:
  name: inbox-zero-svc
  namespace: apps
  labels:
    app: inbox-zero
spec:
  type: ClusterIP
  selector:
    app: inbox-zero
  ports:
    - name: http
      port: 3000
      targetPort: 3000
