apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        backup.velero.io/backup-volumes-excludes: radarr-media
    spec:
      securityContext:
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: radarr-media
          persistentVolumeClaim:
            claimName: pvc-media-nfs
      containers:
        - name: radarr-server
          image: linuxserver/radarr:6.0.4 # {"$imagepolicy": "flux-system:radarr-image-policy"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65533"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-media
              mountPath: /media
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
