apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickstack-operators
  namespace: monitoring
spec:
  interval: 30m
  releaseName: clickstack-operators
  chart:
    spec:
      chart: clickstack-operators
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: clickstack
        namespace: monitoring
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
