apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-helm-repository.yaml
  - grafana-helm-release.yaml
  - opentelemetry-helm-repository.yaml
  - opentelemetry-operator-helm-release.yaml
  - vector-helm-repository.yaml
  - vector-helm-release.yaml
  - victoria-logs-helm-release.yaml
  - victoria-metrics-helm-repository.yaml
  - victoria-metrics-operator-helm-release.yaml
