apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clickstack-helm-repository.yaml
  - clickstack-operators-helm-release.yaml
  - opentelemetry-helm-repository.yaml
  - opentelemetry-operator-helm-release.yaml
