apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: monitoring
spec:
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
  interval: 24h
