apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: monitoring
spec:
  interval: 30m
  releaseName: vector
  chart:
    spec:
      chart: vector
      version: "0.52.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: monitoring
  values:
    role: Agent
    service:
      enabled: false
    serviceHeadless:
      enabled: false
    customConfig:
      data_dir: /vector-data-dir/current
      api:
        enabled: true
        address: 0.0.0.0:8686
      sources:
        kubernetes_logs:
          type: kubernetes_logs
          self_node_name: ${VECTOR_SELF_NODE_NAME}
          read_from: end
          ignore_older_secs: 600
          insert_namespace_fields: false
          pod_annotation_fields:
            container_image_id: ""
            pod_annotations: ""
            pod_ips: ""
            pod_labels: ""
            pod_owner: ""
            pod_uid: ""
          node_annotation_fields:
            node_labels: ""
      sinks:
        victoria_logs:
          type: http
          inputs:
            - kubernetes_logs
          uri: http://victoria-logs-vlogs-server.monitoring.svc.cluster.local:9428/insert/jsonline?_stream_fields=kubernetes.pod_namespace,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_node_name&_msg_field=message&_time_field=timestamp
          compression: gzip
          encoding:
            codec: json
          framing:
            method: newline_delimited
          healthcheck:
            enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
