apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
      annotations:
        backup.velero.io/backup-volumes-excludes: sabnzbd-media
    spec:
      securityContext:
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: sabnzbd-media
          persistentVolumeClaim:
            claimName: pvc-media-nfs
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:5.0.1 # {"$imagepolicy": "flux-system:sabnzbd-image-policy"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: sabnzbd-media
              mountPath: /media
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
