apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces.yaml
  - 01-crds.yaml
  - 02-cilium.yaml
  - 03-storage.yaml
  - 04-external-secrets.yaml
  - 05-secrets.yaml
  - 06-infra-controllers.yaml
  - 07-infra-configs.yaml
  - 08-apps.yaml
  - 09-media.yaml
  - 10-databases.yaml
