apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespaces.yaml
  - 01-crds.yaml
  - 02-storage.yaml
  - 03-external-secrets.yaml
  - 04-secrets.yaml
  - 07-apps.yaml
