apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signoz-certificate
  namespace: observability
spec:
  secretName: signoz-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - signoz.macbytes.io
