apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openobserve-ingressroute
  namespace: openobserve
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openobserve.macbytes.io`)
      kind: Rule
      services:
        - name: openobserve-openobserve-standalone
          port: 5080
  tls:
    secretName: openobserve-tls-certificate
