global:
  cloud: other
  clusterName: geekzoo-prod
  deploymentEnvironment: production

otelCollectorEndpoint: http://signoz-otel-collector.observability.svc.cluster.local:4318
otelInsecure: true

presets:
  otlphttpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  hostMetrics:
    enabled: true
    collectionInterval: 60s
  kubeletMetrics:
    enabled: true
    collectionInterval: 60s
  clusterMetrics:
    enabled: true
    collectionInterval: 60s
  k8sEvents:
    enabled: true
  prometheus:
    enabled: false
  logsCollection:
    enabled: true
    startAt: end
    blacklist:
      enabled: true
      signozLogs: true
      namespaces:
        - kube-system
        - rook-ceph
        - cilium
        - gpu-operator
        - observability
      pods: []
      containers: []
      additionalExclude: []

otelAgent:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

otelDeployment:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
