apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - syslog-gateway-configmap.yaml
  - syslog-gateway-deployment.yaml
  - syslog-gateway-service.yaml
  - kube-prometheus-stack
  - beyla
  - loki
  - tempo
  - promtail
  - grafana-certificate.yaml
  - grafana-ingressroute.yaml
