apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repository.yaml
  - signoz-helm-release.yaml
  - k8s-infra-helm-release.yaml
  - certificate.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: signoz-values
    namespace: observability
    files:
      - values.yaml=signoz-values.yaml
  - name: k8s-infra-values
    namespace: observability
    files:
      - values.yaml=k8s-infra-values.yaml

generatorOptions:
  disableNameSuffixHash: true
