apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repository.yaml
  - object-bucket-claim.yaml
  - openobserve-helm-release.yaml
  - openobserve-collector-helm-release.yaml
  - certificate.yaml
  - ingressroute.yaml
