apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve-collector
  namespace: openobserve
spec:
  interval: 30m
  releaseName: openobserve-collector
  dependsOn:
    - name: opentelemetry-operator
    - name: openobserve
  chart:
    spec:
      chart: openobserve-collector
      version: "0.4.4"
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: openobserve
  valuesFrom:
    - kind: Secret
      name: openobserve-root-user
      valuesKey: collector-values.yaml
  values:
    k8sCluster: geekzoo-prod
    opentelemetry-operator:
      enabled: false
    autoinstrumentation:
      enabled: true
    agent:
      receivers:
        filelog/std:
          include: [/var/log/pods/*/*/*.log]
          exclude:
            - /var/log/pods/*/otel-collector/*.log
            - /var/log/pods/*/otc-container/*.log
            - /var/log/pods/*/openobserve-ingester/*.log
          start_at: beginning
          include_file_path: true
          include_file_name: false
          operators:
            - type: router
              id: get-format
              routes:
                - output: parser-docker
                  expr: 'body matches "^\\{"'
                - output: parser-crio
                  expr: 'body matches "^[^ Z]+ "'
                - output: parser-containerd
                  expr: 'body matches "^[^ Z]+Z"'
            - type: regex_parser
              id: parser-crio
              regex: "^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$"
              output: extract_metadata_from_filepath
              timestamp:
                parse_from: attributes.time
                layout_type: gotime
                layout: "2006-01-02T15:04:05.999999999Z07:00"
            - type: regex_parser
              id: parser-containerd
              regex: "^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$"
              output: extract_metadata_from_filepath
              timestamp:
                parse_from: attributes.time
                layout: "%Y-%m-%dT%H:%M:%S.%LZ"
            - type: json_parser
              id: parser-docker
              output: extract_metadata_from_filepath
              timestamp:
                parse_from: attributes.time
                layout: "%Y-%m-%dT%H:%M:%S.%LZ"
            - type: regex_parser
              id: extract_metadata_from_filepath
              regex: '^.*\/[^_]+_[^_]+_(?P<uid>[^\/]+)\/'
              parse_from: attributes["log.file.path"]
              cache:
                size: 128
            - type: move
              from: attributes.log
              to: body
            - type: move
              from: attributes.stream
              to: attributes["log.iostream"]
            - type: move
              from: attributes.uid
              to: resource["k8s.pod.uid"]
              on_error: send
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    gateway:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
