apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: observability
spec:
  interval: 30m
  timeout: 20m
  releaseName: signoz
  chart:
    spec:
      chart: signoz
      version: "0.127.1"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: signoz-values
      valuesKey: values.yaml
