apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls-certificate
  namespace: media
spec:
  secretName: jellyfin-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - watch.macbytes.io