apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr-ingressroute
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`requests.macbytes.io`)
      kind: Rule
      services:
        - name: seerr
          port: 80
  tls:
    secretName: seerr-tls-certificate
