apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-certificate
  namespace: apps
spec:
  secretName: adguard-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - adguard.macbytes.io
