apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: apps
  labels:
    app: adguard
    app.kubernetes.io/instance: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome:v0.107.74 # {"$imagepolicy": "flux-system:adguardhome-image-policy"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/conf
            - name: adguard-data
              mountPath: /opt/adguardhome/work
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-pvc
