apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - barman-cloud
  - cert-manager
  - chrony
  - cnpg-operator
  - gpu-operator
  - metrics-server
  - rabbitmq-cluster-operator
  - redis-operator
  - traefik
