apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mediamanager-certificate
  namespace: media
spec:
  secretName: mediamanager-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - mediamanager.macbytes.io
