apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: plane-rabbitmq
  namespace: database
spec:
  replicas: 1
  secretBackend:
    externalSecret:
      name: plane-rabbitmq-default-user
  persistence:
    storageClassName: ceph-block
    storage: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  rabbitmq:
    additionalConfig: |
      default_vhost = plane
