hyperdx:
  config:
    FRONTEND_URL: https://clickstack.macbytes.io
    HYPERDX_APP_URL: https://clickstack.macbytes.io
    NEXT_PUBLIC_SERVER_URL: https://clickstack.macbytes.io
    USAGE_STATS_ENABLED: "false"
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 4Gi
  service:
    apiPort:
      enabled: true
  tasks:
    enabled: true

mongodb:
  enabled: true
  spec:
    members: 1
    statefulSet:
      spec:
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 25Gi
          - metadata:
              name: logs-volume
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 5Gi

clickhouse:
  enabled: true
  keeper:
    spec:
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 10Gi
  cluster:
    spec:
      replicas: 1
      shards: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 250Gi
      settings:
        extraConfig:
          max_connections: 4096
          keep_alive_timeout: 64
          max_concurrent_queries: 100

otel-collector:
  enabled: true
  mode: deployment
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  serviceMonitor:
    enabled: true
