apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickstack-clickhouse
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: clickstack-clickhouse-clickhouse
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
