apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clickstack-certificate
  namespace: monitoring
spec:
  secretName: clickstack-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - clickstack.macbytes.io
