apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickstack
  namespace: monitoring
spec:
  dependsOn:
    - name: clickstack-operators
      namespace: monitoring
  interval: 30m
  releaseName: clickstack
  chart:
    spec:
      chart: clickstack
      sourceRef:
        kind: HelmRepository
        name: clickstack
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: clickstack-values
      valuesKey: values.yaml
    - kind: Secret
      name: clickstack-secret-values
      valuesKey: HYPERDX_API_KEY
      targetPath: hyperdx.secrets.HYPERDX_API_KEY
    - kind: Secret
      name: clickstack-secret-values
      valuesKey: CLICKHOUSE_PASSWORD
      targetPath: hyperdx.secrets.CLICKHOUSE_PASSWORD
    - kind: Secret
      name: clickstack-secret-values
      valuesKey: CLICKHOUSE_APP_PASSWORD
      targetPath: hyperdx.secrets.CLICKHOUSE_APP_PASSWORD
    - kind: Secret
      name: clickstack-secret-values
      valuesKey: MONGODB_PASSWORD
      targetPath: hyperdx.secrets.MONGODB_PASSWORD
