apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.macbytes.io
