apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vmsingle.yaml
  - vmagent-rbac.yaml
  - vmagent-scrape-config.yaml
  - vmagent.yaml
  - grafana-datasources.yaml
  - grafana-certificate.yaml
  - grafana-ingressroute.yaml
  - vmalertmanager.yaml
  - vmalert.yaml
  - vmrules.yaml
