apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-prometheus-scraper
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-targetallocator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-prometheus-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - configmaps
      - namespaces
      - nodes
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - probes
      - prometheusrules
      - scrapeconfigs
      - servicemonitors
    verbs:
      - "*"
  - nonResourceURLs:
      - /api
      - /api/*
      - /apis
      - /apis/*
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-prometheus-scraper-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-prometheus-discovery
subjects:
  - kind: ServiceAccount
    name: otel-prometheus-scraper
    namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-targetallocator-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-prometheus-discovery
subjects:
  - kind: ServiceAccount
    name: otel-targetallocator
    namespace: monitoring
