apiVersion: v1
kind: Secret
metadata:
  name: vmagent-additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: kube-apiserver
      static_configs:
        - targets:
            - 192.168.140.4:6443
            - 192.168.135.197:6443
            - 192.168.125.77:6443
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

    - job_name: kubelet
      kubernetes_sd_configs:
        - role: node
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        insecure_skip_verify: true
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels:
            - __meta_kubernetes_node_name
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

    - job_name: cadvisor
      kubernetes_sd_configs:
        - role: node
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        insecure_skip_verify: true
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels:
            - __meta_kubernetes_node_name
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

    - job_name: annotated-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: keep
          source_labels:
            - __meta_kubernetes_namespace_label_monitoring_macbytes_io_scrape
          regex: "true"
        - action: keep
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          regex: "true"
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
          regex: (.+)
        - action: replace
          source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container

    - job_name: kube-state-metrics
      static_configs:
        - targets:
            - kube-state-metrics.monitoring.svc.cluster.local:8080

    - job_name: node-exporter
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - action: keep
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_service_name
            - __meta_kubernetes_endpoint_port_name
          regex: monitoring;node-exporter;metrics
        - action: replace
          source_labels:
            - __meta_kubernetes_endpoint_node_name
          target_label: node

    - job_name: rook-ceph-mgr
      static_configs:
        - targets:
            - rook-ceph-mgr.rook-ceph.svc.cluster.local:9283

    - job_name: rook-ceph-exporter
      static_configs:
        - targets:
            - rook-ceph-exporter.rook-ceph.svc.cluster.local:9926
type: Opaque
