apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicaCount: 1
  configSecret: alertmanager-pushover
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
