apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lingarr-tls-certificate
  namespace: media
spec:
  secretName: lingarr-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - lingarr.macbytes.io
