apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data-pvc
  namespace: mail
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
