apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coroot-certificate
  namespace: coroot
spec:
  secretName: coroot-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - coroot.macbytes.io
