apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: seerr-pg-cluster
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  instances: 3
  enableSuperuserAccess: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: wasabi-object-store
        serverName: seerr-pg-cluster-geekzoo-prod-20260510
  bootstrap:
    initdb:
      database: seerr
      owner: seerr
      secret:
        name: pg-app-user-seerr
  storage:
    storageClass: ceph-block
    size: 5Gi
