apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-certificate
  namespace: apps
spec:
  secretName: website-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - macbytes.io
    - www.macbytes.io
