apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plane-certificate
  namespace: plane
spec:
  secretName: plane-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - plane.macbytes.io
