apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-pg-cluster-backup
  namespace: database
spec:
  cluster:
    name: vaultwarden-pg-cluster-20260401
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
