apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vikunja-pg-cluster-backup
  namespace: database
spec:
  cluster:
    name: vikunja-pg-cluster
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
