apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 30m
  releaseName: tempo
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
      valuesKey: values.yaml
