operatorNamespace: rook-ceph
configOverride: |
  [global]
  debug_default = 0/5
  debug_mon = 0/5
  debug_mgr = 0/5
  debug_osd = 0/5
  debug_rgw = 0/5
cephClusterSpec:
  removeOSDsIfOutAndSafeToRemove: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "talos-node-01"
      devices:
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677721"
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677722"
    - name: "talos-node-02"
      devices:
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677206"
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677713"
    - name: "talos-node-03"
      devices:
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677283"
        - name: "/dev/disk/by-id/nvme-SAMSUNG_MZ1LB1T9HALS-00007_S436NC0R677465"
ingress:
  dashboard:
    enabled: true
monitoring:
  enabled: false
  createPrometheusRules: false
toolbox:
  enabled: true
