operatorNamespace: rook-ceph
cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "talos-node-01"
      devices:
        - name: "nvme0n1"
        - name: "nvme1n1"
    - name: "talos-node-02"
      devices:
        - name: "nvme0n1"
        - name: "nvme1n1"
    - name: "talos-node-03"
      devices:
        - name: "nvme0n1"
        - name: "nvme2n1"
ingress:
  dashboard:
    enabled: true
monitoring:
  enabled: false
  createPrometheusRules: false
toolbox:
  enabled: true