apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui-certificate
  namespace: apps
spec:
  secretName: open-webui-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - chat.macbytes.io
