apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: minecraft-helm-values
    namespace: apps
    files:
      - values.yaml=helm-values.yaml

generatorOptions:
  disableNameSuffixHash: true
